### ISSUE TITLE
Update libsedml to > 2.0.10

### ISSUE THREAD

**Issue by fbergmann** [reproducible-biomedical-modeling/Biosimulations_utils#19]
I was wondering whether there is a specific issue with the current version of libsedml, that you would require

`python_libsedml >= 2, <= 2.0.9`

thanks

**Comment by jonrkarr** [comment]
My memory is hazy because this was a couple months ago. I think was a runtime error with 2.0.10.

**Comment by fbergmann** [comment]
All the changes that have been made since 2.0.9 (March 19th) were build system related, so that the python bindings could be generated without too many manual steps: 

https://github.com/fbergmann/libSEDML/commits/level1-version4

I'm making another sweep as to possible sources of the runtime errors, but without more of a hint i'm not sure where they could be coming from.

**Comment by jonrkarr** [comment]
I posted the issue to fbergmann/libSEDML#78. When this is resolved, we will update our dependency.

**Comment by jonrkarr** [comment]
Updated to 2.0.11 which seems to work well.
